name: Run Unit Tests

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Baixa o repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # Instala o .NET SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' 


    - name: Restore dependencies
      run: dotnet restore backend/TaskManager.API/TaskManager.API.csproj


    - name: Build project
      run: dotnet build backend/TaskManager.API/TaskManager.API.csproj --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test backend/TaskManager.API/TaskManager.API.csproj --configuration Release --no-build --verbosity normal
