name: Run Unit Tests

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Baixa o repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # Instala o .NET SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' 

    # Restaura as dependências
    - name: Restore dependencies
      run: dotnet restore

    # Compila o projeto
    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # Executa os testes
    - name: Run unit tests
      run: dotnet test --configuration Release --no-build --verbosity normal
